---
abstract: 'Interact with Gallery via the Gallery Remote Protocol'
author:
  - 'Jonathan Wright <mysteryte@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gallery-Remote-API
provides:
  Gallery::Remote::API:
    file: lib/Gallery/Remote/API.pm
    version: v0.1.4
requires:
  Class::Accessor: 0
  Config::Properties: 0
  Data::Diver: 0
  Data::Dumper: 0
  Fcntl: 0
  File::Temp: 0
  Getopt::Long: 0
  HTTP::Cookies: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Sub::Name: 0
  Test::Mock::LWP: 0
  Test::More: 0
  URI: 0
  URI::QueryParam: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.1.4
